blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/urls.py
from django.urls import path
from . import views
app_name = 'core'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('post/<int:id>/', views.detail, name= 'detail'),

]

core/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField


class Post(models.Model):
    #title

    title = models.CharField('Título', max_length= 500, blank= False, null= False)
    #resumo
    resume =models.TextField(default='')
    #conteudo
    content = RichTextField()
    #data de publi
    date_published = models.DateField('Data da Publicação', auto_now_add= True)
    #slug
    slug = models.SlugField('Slug', editable=False)


    def __str__(self):
       return self.title

    def save(self, *args, **kwargs):

        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args,**kwargs)

core/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.

def index(request):
    posts = Post.objects.all().order_by('-id')
    data = {

        'post_list': posts,
    }
    print('============',posts)
    return render(request, 'core/index.html', data)

def detail(request, id):
    post = Post.objects.get(id=id)
    data = {

        'post': post
    }
    return render(request, 'core/detail.html', data)

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meu Blog</title>
    <link rel ="stylesheet" href="{% static 'css/main.css' %}"



</head>
<body>
<section class="hero is-medium is-link">
  <div class="hero-body has-text-centered">
    <p class="title">
      Bem vindo ao meu blog
    </p>
    <p class="subtitle has-text-centered">
      Blog Criando no curso backend com django
    </p>
  </div>
</section>

    {%block content%}
    {% endblock %}



<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Meu Blog</strong> by <a href="https://ohmycode.com.br">OhMyCode</a>
        <strong>Admin</strong> by <a href="http://127.0.0.1:8000/admin">Arthur</a>
    </p>
  </div>
</footer>

</body>

core/templates/core/detail.html
{% extends './base.html'%}

{% block content %}
<section class="section is-small">
  <div class="container">
      <h1 class="title">{{ post.title }}</h1>
    <div class="wysiwyg">
    {{post.content |safe }}
    </div>
  </div>
</section>

{% endblock %}

core/templates/core/index.html
{% extends './base.html'%}

{% block content %}


 {%if post_list%}
   {% for post in post_list %}
   <section class="section is-small">
     <h1 class="title"><a href="{% url 'core:detail' post.id %}">{{post.title}}</a> </h1>
     <h2 class="subtitle">
      {{post.resume}}
     </h2>
   </section>
   {% endfor %}
 {%else%}
  <section class="section is-small">
    <h1 class="title">nao existe post cadastrado/h1>

  </section>
 {%endif%}

{% endblock %}

core/templates/core/post1.html
{% extends './base.html'%}

{% block content %}

<section class="section is-small">
  <h1 class="title"><a href="http://127.0.0.1:8000/">Post numero - 1</h1>
  <h2 class="subtitle">
   Noticia sobre o glorioso!!
  </h2>

    <img src="https://seeklogo.com/images/B/Botafogo_de_Futebol_e_Regatas_do_Rio_de_Janeiro-RJ-logo-A64D2518DA-seeklogo.com.png">
    <p>
         Gilvan deve permanecer no Botafogo por mais um ano. Contratado no início da temporada,
         o zagueiro tem contrato que prevê renovação automática até o fim de 2022 em caso de acesso para a Série A.
         A informação é do “Canal do Medeiros”.
    </p>
</section>

{% endblock %}

core/templates/core/post2.html
{% extends './base.html'%}

{% block content %}

<section class="section is-small">
  <h1 class="title">Post numero - 2</h1>
  <h2 class="subtitle">
    A simple container to divide your page into <strong>sections</strong>, like the one you're currently reading.
  </h2>
</section>

{% endblock %}

core/templates/core/post3.html
{% extends './base.html'%}

{% block content %}

<section class="section is-small">
  <h1 class="title">Post numero - 3</h1>
  <h2 class="subtitle">
    A simple container to divide your page into <strong>sections</strong>, like the one you're currently reading.
  </h2>
</section>

{% endblock %}